{"infos":[
{
    "index": 0,
    "type":"period",
    "page":"residency",
    "images": ["img/residency/period.jpg"],
    "start-date": "1999-10-01",
    "end-date": "2001-01-01",
    "title": "The Moving Truck",
    "lead": null,
    "collaborators": [],
    "countdown": false,
    "countdown-days": null,
    "icon": "img/residency/period.jpg",
    "description-past": "between October 1999 and January 2001, the residency <strong>lived</strong> in a truck--a moivng truck.",
    "description-present": "between October 1999 and January 2001, the residency <strong>lives</strong> in a truck--a moivng truck.",
    "description-future": "between October 1999 and January 2001, the residency <strong>will live</strong> in a truck--a moivng truck."
},
{   "index": 1,
    "type":"archives",
    "page":"residency",
    "images": ["img/residency/archive.jpg"],
    "start-date": "2001-01-01",
    "end-date": "2020-01-01",
    "title": "The University Basement",
    "lead": null,
    "collaborators": [],
    "countdown": false,
    "countdown-days": null,
    "icon": "img/residency/period.jpg",
    "description-past": "University basements <strong>>were</strong> connected with tunnels.",
    "description-present": "University basements <strong>>are</strong> connected with tunnels.",
    "description-future": "University basements <strong>>will be</strong> connected with tunnels."
},
{   "index": 2,
    "type":"period",
    "page":"residency",
    "images": ["img/residency/period.jpg"],
    "start-date": "2020-01-01",
    "end-date": "2024-01-01",
    "title": "The middle room",
    "lead": null,
    "collaborators": [],
    "countdown": false,
    "countdown-days": null,
    "icon": "img/residency/period.jpg",
    "description-past": "<strong>Those were</strong> the days of middle rooms.",
    "description-present": "<strong>These are</strong> the days of middle rooms.",
    "description-future": "<strong>These will be</strong> the days of middle rooms"
},
{   "index": 3,
    "type":"archives",
    "page":"residency",
    "images": ["img/residency/archives.jpg"],
    "start-date": "2000-10-01",
    "end-date": "2000-10-30",
    "title": "All my Stuff",
    "lead": "Francis Fullscript",
    "collaborators": [],
    "countdown": false,
    "countdown-days": null,
    "icon": "img/residency/2000-10-01.jpg",
    "description-past": "",
    "description-present": "Fullscript evaluates his life, as it stacks like tetris peices into a moving truck going nowhere.",
    "description-future": ""
},
{   "index": 4,
    "type":"archives",
    "page":"residency",
    "images": ["img/residency/period.jpg"],
    "start-date": "2019-10-01",
    "end-date": "2019-11-31",
    "title": "Art in Movies",
    "lead": "Jodie Vermeer",
    "collaborators": [],
    "countdown": false,
    "countdown-days": null,
    "icon": "img/residency/2019-10-01.jpg",
    "description-past": "",
    "description-present": "Art in the movies is art for the movies. It benefits from a narrow context. To anyone who knows about the art world, it looks like something made by a novice--probably the director's brother-in-law.",
    "description-future": ""
}
]}