---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mcandide/public_html/
    - /bin/cp -R favicon_io $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R infos $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH